version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "SONARTOKEN"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    HOST: "HOST"
    ORGANIZATION: "ORGANIZATION"
    PROJECT: "PROJECT"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven and setting up CodeArtifact..."
      - aws codeartifact login --tool maven --domain $HOST --domain-owner $ORGANIZATION --repository $PROJECT --region us-east-1
      - mvn --version

  pre_build:
    commands:
      - echo "Preparing environment..."
      - export SONAR_TOKEN=$(aws ssm get-parameter --name SONARTOKEN --with-decryption --query Parameter.Value --output text)
      - export CODEARTIFACT_TOKEN=$(aws ssm get-parameter --name CODEARTIFACT_TOKEN --with-decryption --query Parameter.Value --output text)
      - echo "Environment setup completed."
  build:
    commands:
      - echo "Running SonarQube Code Analysis..."
      - mvn sonar:sonar \
        -Dsonar.host.url=$HOST \
        -Dsonar.organization="$ORGANIZATION" \
        -Dsonar.projectKey=$PROJECT \
        -Dsonar.login=$SONARTOKEN

artifacts:
  files:
    - "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
