version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "SONARTOKEN"
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN"
    HOST: "HOST"
    ORGANIZATION: "ORGANIZATION"
    PROJECT: "PROJECT"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Maven and setting up CodeArtifact..."
      - aws codeartifact login --tool maven --domain $HOST --domain-owner $ORGANIZATION --repository $PROJECT --region us-west-2
      - mvn --version

  pre_build:
    commands:
      - echo "Preparing environment..."
      - export SONAR_TOKEN=$(aws ssm get-parameter --name SONARTOKEN --with-decryption --query Parameter.Value --output text)
      - export CODEARTIFACT_TOKEN=$(aws ssm get-parameter --name CODEARTIFACT_TOKEN --with-decryption --query Parameter.Value --output text)
      - echo "Environment setup completed."

  build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean install -DskipTests
      - echo "Running unit tests..."
      - mvn test
      - echo "Running integration tests..."
      - mvn verify -DskipUnitTests
      - echo "Performing static code analysis with Checkstyle..."
      - mvn checkstyle:checkstyle
      - echo "Uploading to SonarQube..."
      - sonar-scanner \
        -Dsonar.projectKey=$PROJECT \
        -Dsonar.projectName=$PROJECT-repo \
        -Dsonar.projectVersion=1.0 \
        -Dsonar.sources=src/ \
        -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/ \
        -Dsonar.junit.reportsPath=target/surefire-reports/ \
        -Dsonar.jacoco.reportsPath=target/jacoco.exec \
        -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml \
        -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - echo "Publishing artifacts to CodeArtifact..."
      - mvn deploy -DaltDeploymentRepository=releases::default::https://$HOST.d.codeartifact.us-east-1.amazonaws.com/maven/$PROJECT/
      - echo "Build and publishing completed successfully."

artifacts:
  files:
    - target/**/*
