version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies and retrieving environment variables from SSM Parameter Store..."
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo "Retrieving parameters from SSM..."
      - export CODEARTIFACT_TOKEN=$(aws ssm get-parameter --name "CODEARTIFACT_TOKEN" --with-decryption --query "Parameter.Value" --output text)
      - export HOST=$(aws ssm get-parameter --name "HOST" --query "Parameter.Value" --output text)
      - export ORGANIZATION=$(aws ssm get-parameter --name "ORGANIZATION" --query "Parameter.Value" --output text)
      - export PROJECT=$(aws ssm get-parameter --name "PROJECT" --query "Parameter.Value" --output text)
      - export SONARTOKEN=$(aws ssm get-parameter --name "SONARTOKEN" --with-decryption --query "Parameter.Value" --output text)
      - echo "Parameters retrieved: HOST=$HOST, ORGANIZATION=$ORGANIZATION, PROJECT=$PROJECT"

  build:
    commands:
      - echo "Running SonarQube Code Analysis..."
      - mvn sonar:sonar \
        -Dsonar.host.url=$HOST \
        -Dsonar.organization="$ORGANIZATION" \
        -Dsonar.projectKey=$PROJECT \
        -Dsonar.login=$SONARTOKEN

artifacts:
  files:
    - "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
