version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "SONARTOKEN" # The SSM parameter name is SONARTOKEN
    CODEARTIFACT_TOKEN: "CODEARTIFACT_TOKEN" # The SSM parameter name is CODEARTIFACT_TOKEN
    HOST: "HOST" # The SSM parameter name is HOST
    ORGANIZATION: "ORGANIZATION" # The SSM parameter name is ORGANIZATION
    PROJECT: "PROJECT" # The SSM parameter name is PROJECT
    CODEARTIFACT_DOMAIN: "/codeartifact/domain" # The SSM parameter name for CodeArtifact domain
    CODEARTIFACT_OWNER: "/codeartifact/owner" # The SSM parameter name for CodeArtifact owner

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - aws codeartifact login --tool mvn --domain $(aws ssm get-parameter --name "/codeartifact/domain" --query Parameter.Value --output text) --domain-owner $(aws ssm get-parameter --name "/codeartifact/owner" --query Parameter.Value --output text)

  build:
    commands:
      - mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=$PROJECT \
        -Dsonar.organization=$ORGANIZATION \
        -Dsonar.host.url=$HOST \
        -Dsonar.login=$SONAR_TOKEN \
        -Dsonar.java.jdkHome=/usr/lib/jvm/java-17-amazon-corretto.x86_64
artifacts:
  files:
    - "**/*"
  discard-paths: yes

cache:
  paths:
    - "/root/.m2/**/*"
